Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Vagrant up succeeded"
  config.vm.network "public_network", bridge: "enp0s31f6"
  config.vm.hostname = "Romain"

  config.vm.define "Romain" do |Romain|
    Romain.vm.box = "dev2ops/kube"
  end
end
