Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"
  config.vm.network "public_network", bridge: "enp0s31f6"
  config.vm.hostname = "m2i"

  config.vm.define "host1" do |host1|
    host1.vm.box = "custombox/ubundock.box"
  end
end
